const employees = [
  {
    employeeId: 1,
    name: "Rahul Sharma",
    email: "rahul.sharma@example.com",
    departmentId: 1,
    roleId: 1,
  },
  {
    employeeId: 2,
    name: "Priya Singh",
    email: "priya.singh@example.com",
    departmentId: 2,
    roleId: 2,
  },
  {
    employeeId: 3,
    name: "Amit Verma",
    email: "amit.verma@example.com",
    departmentId: 3,
    roleId: 3,
  },
  {
    employeeId: 4,
    name: "Sita Yadav",
    email: "sita.yadav@example.com",
    departmentId: 1,
    roleId: 2,
  },
  {
    employeeId: 5,
    name: "Rajesh Kumar",
    email: "rajesh.kumar@example.com",
    departmentId: 2,
    roleId: 1,
  },
  {
    employeeId: 6,
    name: "Neha Gupta",
    email: "neha.gupta@example.com",
    departmentId: 3,
    roleId: 2,
  },
  {
    employeeId: 7,
    name: "Anil Joshi",
    email: "anil.joshi@example.com",
    departmentId: 1,
    roleId: 1,
  },
  {
    employeeId: 8,
    name: "Monika Sharma",
    email: "monika.sharma@example.com",
    departmentId: 2,
    roleId: 3,
  },
  {
    employeeId: 9,
    name: "Deepak Mehra",
    email: "deepak.mehra@example.com",
    departmentId: 3,
    roleId: 1,
  },
  {
    employeeId: 10,
    name: "Sonali Verma",
    email: "sonali.verma@example.com",
    departmentId: 1,
    roleId: 2,
  },
  {
    employeeId: 11,
    name: "Vijay Singh",
    email: "vijay.singh@example.com",
    departmentId: 2,
    roleId: 1,
  },
  {
    employeeId: 12,
    name: "Kavita Patel",
    email: "kavita.patel@example.com",
    departmentId: 3,
    roleId: 3,
  },
  {
    employeeId: 13,
    name: "Rohit Chauhan",
    email: "rohit.chauhan@example.com",
    departmentId: 1,
    roleId: 3,
  },
  {
    employeeId: 14,
    name: "Anjali Reddy",
    email: "anjali.reddy@example.com",
    departmentId: 2,
    roleId: 2,
  },
  {
    employeeId: 15,
    name: "Sameer Ali",
    email: "sameer.ali@example.com",
    departmentId: 3,
    roleId: 1,
  },
];

module.exports = { employees };
